### ISSUE TITLE
Cascade/ delay effect across lights/ entities

### ISSUE THREAD

**Issue by IS512** [PaulSD/ha_color_loop#1]
Will the ability to cascade/ spread the effect across multiple entities be worked on? 

(I.e not having the same colour value across entities)

**Comment by PaulSD** [comment]
That wasn't one of my goals ... And it isn't clear to me how it would fit into the current design.

For example, the current code is designed around a single set of state variables (tracking a single color sequence), and supporting a cascade effect would require splitting that to multiple states (one for each entity or active color) and mutating them independently but synchronously, which would probably require a complete redesign.
It also isn't clear to me what the configuration UI would look like, or what inputs would be used to manage this.

If there is an obvious way (that I am missing) to incorporate this easily, then I might consider it.  Otherwise, this is out of the scope of what I am planning.
